In [12]:
import numpy as np

matrix_a = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [3, 35, 23]
])
          
x=np.array([[1],
 [2],
 [9]])
c=matrix_a@x
print(c)

[[ 52]
 [104]
 [280]]


In [14]:
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [ 3.57123152e+01 -8.73888462e-16 -5.71231518e+00]
Eigenvectors:
 [[-0.16227293 -0.96861228 -0.29534503]
 [-0.32454585 -0.07310281 -0.59069007]
 [-0.93184628  0.23758414  0.75090383]]
